In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('linkminer_betterhelp_com.csv')
df.head()

Backlink URL  \
0                        https://goodmenproject.com/   
1                       https://mysupportforums.org/   
2         https://www.211.org/get-help/substance-use   
3  https://www.verywellmind.com/best-online-thera...   
4                     https://www.teladochealth.com/   

                                               Title  \
0  The Good Men Project - The Conversation No One...   
1                                  My Support Forums   
2                     Substance Use | United Way 211   
3  The 8 Best Online Therapy Companies We’ve Test...   
4  Telehealth & Telemedicine Provider | Teladoc H...   

                                          Target URL  \
0          https://www.betterhelp.com/goodmenproject   
1             https://betterhelp.com/mysupportforums   
2  https://www.betterhelp.com/start/?go=true&tran...   
3  http://betterhelp.com/verywell/?aff_sub2=46912...   
4  https://www.betterhelp.com/teladoc-health/?aff...   

                                              Anchor  Citation Flow  \
0                                         betterhelp             44   
1  consider betterhelp online counseling & get 20...             47   
2                                         betterhelp             43   
3                                         betterhelp             53   
4                                         betterhelp             49   

   Trust Flow  Website Popularity Rank  Facebook Shares  Link Strength  \
0          63                  22903.0          19404.0             70   
1          54                      NaN              NaN             31   
2          56                  71544.0             11.0             60   
3          45                   3226.0           1258.0             42   
4          49                  47030.0           1353.0             64   

   External Links  Internal Links  Flag: Alt  Flag: Deleted  Flag: Frame  \
0            63.0           202.0      False          False        False   
1             6.0           283.0      False          False        False   
2            34.0            72.0      False          False        False   
3            49.0           186.0      False          False        False   
4            37.0           112.0      False          False        False   

   Flag: Image  Flag: Mention  Flag: NoFollow  Flag: Redirect  
0        False          False           False           False  
1        False          False            True           False  
2        False          False           False           False  
3        False          False            True           False  
4        False          False           False           False

In [3]:
df['Title'] = df['Title'].astype('str')

In [5]:
len(df['Title'])

443

In [4]:
import nltk
from nltk.corpus import stopwords

lemmatizer = nltk.stem.WordNetLemmatizer()

# 1. Term-document matrix and cleaning the data

In [53]:
processed_coll = []
for doc in df['Title']:
    tokens = nltk.word_tokenize(doc.lower())
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token.isalpha()]
    tokens = [token for token in tokens if not token in stopwords.words('english')]
    processed_coll.append(' '.join(tokens))
    
print(processed_coll)

['good men project conversation one else', 'support forum', 'substance use united way', 'best online therapy company tested', 'telehealth telemedicine provider teladoc health', 'sleep profile sleep foundation', 'society medicine smfm', 'listening audacy', 'mental health resource bungie help', 'find therapist therapy provider reviewed', 'understand fact anxiety depression association america adaa', 'sponsor', 'dalrymple report watch charging stand ipad mini submerged', 'everything everywhere sponsor', 'swimm ai code documentation knowledge sharing', 'minnesota judicial branch jury service minnesota judicial branch', 'digitalen beenden tipps', 'step getting breakup moving', 'advertise u canadaland', 'external resource scarleteen', 'awesome etiquette podcast emily post', 'date night idea howstuffworks', 'aafs follow american academy forensic science', 'tricky question ask boyfriend test', 'mighty group directory mighty mighty', 'welcome night vale', 'counseling service salve regina univer

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [55]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=5)
vector_transform = vectorizer.fit_transform(processed_coll)
terms = vectorizer.get_feature_names_out()
vector_transform_array = vector_transform.toarray()

In [56]:
output_df = pd.DataFrame(vector_transform_array, columns=terms)
output_df

addiction  american  anxiety  apps  association     best  best online  \
0          0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
1          0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
2          0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
3          0.0       0.0      0.0   0.0          0.0  0.42131     0.501757   
4          0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
..         ...       ...      ...   ...          ...      ...          ...   
438        0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
439        0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
440        0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
441        0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   
442        0.0       0.0      0.0   0.0          0.0  0.00000     0.000000   

     betterhelp      care  center  ...  top  treatment  type  university  \
0           0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
1           0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
2           0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
3           0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
4           0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
..          ...       ...     ...  ...  ...        ...   ...         ...   
438         0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
439         0.0  0.441312     0.0  ...  0.0        0.0   0.0    0.398810   
440         0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   
441         0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.445559   
442         0.0  0.000000     0.0  ...  0.0        0.0   0.0    0.000000   

          use       way  wellness  woman  work  world  
0    0.000000  0.000000  0.000000    0.0   0.0    0.0  
1    0.000000  0.000000  0.000000    0.0   0.0    0.0  
2    0.716333  0.697759  0.000000    0.0   0.0    0.0  
3    0.000000  0.000000  0.000000    0.0   0.0    0.0  
4    0.000000  0.000000  0.000000    0.0   0.0    0.0  
..        ...       ...       ...    ...   ...    ...  
438  0.000000  0.000000  0.000000    0.0   0.0    0.0  
439  0.000000  0.000000  0.407577    0.0   0.0    0.0  
440  0.000000  0.000000  0.000000    0.0   0.0    0.0  
441  0.000000  0.000000  0.000000    0.0   0.0    0.0  
442  0.000000  0.000000  0.000000    0.0   0.0    0.0  

[443 rows x 74 columns]

# 2. LDA model to extract topics. Topics = 6

In [89]:
from sklearn.decomposition import LatentDirichletAllocation
lda_title = LatentDirichletAllocation(n_components=6).fit(vector_transform)

In [90]:
title_topic_distribution = lda_title.transform(vector_transform)

# 3. Topic distribution and top 2 topics of first 10 page titles for testing

In [91]:
first_10_title = title_topic_distribution[0:10]
print(first_10_title)

[[0.06911018 0.06911054 0.06911009 0.65418163 0.06922506 0.0692625 ]
 [0.08333358 0.5831517  0.08351364 0.08333364 0.08333373 0.08333371]
 [0.0690401  0.06986615 0.6536621  0.06904041 0.06904075 0.06935049]
 [0.74146409 0.05166414 0.05163883 0.05167509 0.05163895 0.05191891]
 [0.08333345 0.08333353 0.58333252 0.08333348 0.08333352 0.08333351]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.04884191 0.04884214 0.6103029  0.19432889 0.04884209 0.04884207]
 [0.06138137 0.06127019 0.06127004 0.06127012 0.06127016 0.69353812]]


In [92]:
top_2_topics_titles = np.argsort(-first_10_title)[:, :2]
for i, topics in enumerate(top_2_topics_titles):
    print(f"Title {i}: Top 2 topics are {topics[0]} and {topics[1]}")

Title 0: Top 2 topics are 3 and 5
Title 1: Top 2 topics are 1 and 2
Title 2: Top 2 topics are 2 and 1
Title 3: Top 2 topics are 0 and 5
Title 4: Top 2 topics are 2 and 1
Title 5: Top 2 topics are 0 and 1
Title 6: Top 2 topics are 0 and 1
Title 7: Top 2 topics are 0 and 1
Title 8: Top 2 topics are 2 and 3
Title 9: Top 2 topics are 5 and 0


# 4. Top terms for each topic

In [93]:
for topic_idx, topic in enumerate(lda_title.components_):
    print("Topic %d:" % (topic_idx))
    print(" ".join([terms[i] for i in topic.argsort()[:-6-1:-1]]))

Topic 0:
online podcast best service online therapy counseling
Topic 1:
relationship support woman wellness people home
Topic 2:
resource health mental health mental student health resource
Topic 3:
love help men guide partner chat
Topic 4:
family center psychology question night know
Topic 5:
therapy sponsor sign therapist find treatment
